# base class that should be imported on all cluster classes
#

parameters:

  provider:
    google:
      project: ${name}
      credentials: '~/.config/credentials.json'
      version: 1.6.0
      region: ${main_region}
      zone:  ${main_zone}

  terraform:
    backend:
      gcs:
        bucket: my_centralized_tf_bucket
        project: centralized_gcloud_project
        prefix: /${name}/

  synthnetes:
    vars:
      target: ${name}
    compile:
      - output_path: manifests
        output_type: json
        input_paths:
          - templates/main.jsunset
        input_type: jsunset
