from lab.envs.toy_text.blackjack import BlackjackEnv
from lab.envs.toy_text.roulette import RouletteEnv
from lab.envs.toy_text.frozen_lake import FrozenLakeEnv
from lab.envs.toy_text.nchain import NChainEnv
from lab.envs.toy_text.hotter_colder import HotterColder
from lab.envs.toy_text.guessing_game import GuessingGame
from lab.envs.toy_text.kellycoinflip import KellyCoinflipEnv
from lab.envs.toy_text.kellycoinflip import KellyCoinflipGeneralizedEnv
from lab.envs.toy_text.cliffwalking import CliffWalkingEnv
