from lab.monitoring.stats_recorder import StatsRecorder
from lab.monitoring.video_recorder import VideoRecorder
from lab.wrappers.monitoring import load_results, detect_training_manifests, load_env_info_from_manifests, _open_monitors