apiVersion: v1
kind: Service
metadata:
  labels:
    name: example-mysql-jsunset
  name: example-mysql-jsunset
  namespace: minikube-mysql
spec:
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    name: example-mysql
  type: ClusterIP
