apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: ?{gpg:mysql/root/password:20632339}
kind: Secret
metadata:
  labels:
    name: example-mysql
  name: example-mysql
  namespace: minikube-mysql
type: Opaque
