language: python

python:
  - "3.6"

branches:
  only:
    - master

notifications:
  recipients:
    - buriola@google.com
    - ramaro@google.com
    - ademaria@google.com
    - chifor@google.com
  email:
    on_success: change
    on_failure: always

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gnupg2 git

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python run_tests.py
