sudo: required
language: python
python:
  - "3.6"
services:
  - docker
# Workaround for https://github.com/travis-ci/travis-ci/issues/5246
env:
  - BOTO_CONFIG=/tmp/nowhere
install:
  - "pip install -r requirements.txt"
  - "mkdir -p ~/.kube"
  - "ln -s $PWD/test/data/kube_config.yaml ~/.kube/config"
script:
  - "nosetests test/"
  - "mypy --ignore-missing-imports autoscaler/azure_api.py"
  - "docker build ."
cache: pip
